// Generated by ../build-firefox.mjs; edit shared sources.
const domains = Object.freeze({claude: ['claude.ai'], codex: ['chatgpt.com', 'auth.openai.com'], grok: ['grok.com', 'auth.x.ai']});
const DEFAULT_STORE = typeof browser !== 'undefined' && typeof browser.runtime?.getBrowserInfo === 'function' ? 'firefox-default' : '0';
function allowedHost(provider, host) {
  return Object.hasOwn(domains, provider) && typeof host === 'string' && domains[provider].some(root => host === root || (!root.startsWith('auth.') && host.endsWith('.' + root)));
}
function validateCookies(provider, cookies, now = Date.now() / 1000, store = DEFAULT_STORE) {
  if (!['0', 'firefox-default'].includes(store)) throw Error('Unsupported cookie store');
  if (!Object.hasOwn(domains, provider) || !Array.isArray(cookies) || !cookies.length || cookies.length > 500) throw Error('Invalid session');
  const keys = new Set();
  for (const c of cookies) {
    if (!c || typeof c !== 'object' || typeof c.domain !== 'string' || !/^\.?[a-z0-9.-]+$/.test(c.domain) || !allowedHost(provider, c.domain.replace(/^\./, '')) ||
      typeof c.name !== 'string' || !c.name.length || /[\x00-\x20\x7f;,=]/.test(c.name) || typeof c.value !== 'string' || /[\x00-\x1f\x7f]/.test(c.value) || c.value.length > 65536 ||
      typeof c.path !== 'string' || !c.path.startsWith('/') || /[\x00-\x20\x7f?#]/.test(c.path) ||
      typeof c.hostOnly !== 'boolean' || typeof c.secure !== 'boolean' || typeof c.httpOnly !== 'boolean' || typeof c.session !== 'boolean' ||
      !['no_restriction', 'lax', 'strict', 'unspecified'].includes(c.sameSite) || c.storeId !== store || c.partitionKey != null || (c.firstPartyDomain != null && c.firstPartyDomain !== '') ||
      (!c.session && (!Number.isFinite(c.expirationDate) || c.expirationDate <= now)) ||
      (c.hostOnly && c.domain.startsWith('.'))) throw Error('Unsupported or expired session');
    const key = `${c.domain}|${c.path}|${c.name}`;
    if (keys.has(key)) throw Error('Duplicate cookie');
    keys.add(key);
  }
  return cookies;
}
function cookieURL(c) { return `https://${c.domain.replace(/^\./, '')}${c.path}`; }
function cookieDetails(c) {
  const d = {url: cookieURL(c), name: c.name, value: c.value, path: c.path, secure: c.secure, httpOnly: c.httpOnly, sameSite: c.sameSite, storeId: c.storeId};
  if (!c.hostOnly) d.domain = c.domain;
  if (!c.session) d.expirationDate = c.expirationDate;
  return d;
}
async function readCookies(api, provider, store = DEFAULT_STORE) {
  if (!domains[provider]) throw Error('Unsupported provider');
  if (!['0', 'firefox-default'].includes(store)) throw Error('Unsupported cookie store');
  const all = await api.getAll({storeId: store});
  const selected = all.filter(c => allowedHost(provider, c.domain.replace(/^\./, '')));
  if (selected.some(c => c.storeId !== store || c.partitionKey != null || (c.firstPartyDomain != null && c.firstPartyDomain !== ''))) throw Error('Partitioned sessions unsupported');
  return selected;
}
async function replace(api, provider, target, store) {
  for (const c of await readCookies(api, provider, store)) {
    const result = await api.remove({url: cookieURL(c), name: c.name, storeId: store});
    if (!result) throw Error('Cookie removal failed');
  }
  for (const c of target) {
    if (!await api.set(cookieDetails(c))) throw Error('Cookie write failed');
  }
  const actual = await readCookies(api, provider, store);
  const normalize = cookies => cookies.map(c => JSON.stringify([c.domain.replace(/^\./, ''), c.hostOnly, c.name, c.value, c.path, c.secure, c.httpOnly, c.sameSite, c.session, c.session ? null : Math.floor(c.expirationDate)])).sort();
  if (JSON.stringify(normalize(actual)) !== JSON.stringify(normalize(target))) throw Error('Cookie verification failed');
}
async function applySession(api, provider, target, store = DEFAULT_STORE) {
  validateCookies(provider, target, Date.now() / 1000, store);
  const previous = await readCookies(api, provider, store);
  if (previous.length) validateCookies(provider, previous, Date.now() / 1000, store);
  try { await replace(api, provider, target, store); }
  catch {
    try { await replace(api, provider, previous, store); }
    catch { throw Error('Session failed; rollback failed. Sign in manually.'); }
    throw Error('Session failed; previous cookies restored.');
  }
}

const HOST = 'com.local.subscriptionbar';
let port, instanceID, accounts = [], status = 'Connecting to SubscriptionBar…', polling = false;
let queue = Promise.resolve();
const requests = new Map(), processing = new Set();
function serialize(fn) { const next = queue.then(fn); queue = next.catch(() => {}); return next; }
function rpc(payload) {
  if (!port) return Promise.reject(Error('SubscriptionBar is unavailable'));
  const requestID = crypto.randomUUID();
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => { requests.delete(requestID); reject(Error('SubscriptionBar timed out')); }, 15000);
    requests.set(requestID, {resolve, reject, timer});
    port.postMessage({...payload, browserInstanceID: instanceID, requestID});
  });
}
function validAccount(a) { return a && typeof a.id === 'string' && a.id.length > 0 && a.id.length < 200 && typeof a.label === 'string' && a.label.length < 300 && Object.hasOwn(domains, a.provider); }
async function poll() {
  if (polling || !port) return;
  polling = true;
  try {
    const response = await rpc({op: 'hello'});
    if (response.ok !== true || !Array.isArray(response.accounts) || !response.accounts.every(validAccount) || !Array.isArray(response.pending)) throw Error('Invalid host response');
    accounts = response.accounts;
    if (status.startsWith('Connecting') || status.startsWith('SubscriptionBar')) status = 'Connected';
    for (const command of response.pending) {
      if (!command || command.op !== 'activate' || typeof command.id !== 'string' || command.id.length > 200 || !accounts.some(a => a.id === command.accountID && a.provider === command.provider) || processing.has(command.id)) continue;
      processing.add(command.id);
      serialize(async () => {
        const {completed = [], lastResult, receipts = []} = await browser.storage.local.get(['completed', 'lastResult', 'receipts']);
        const receipt = receipts.find(r => r.commandID === command.id);
        if (receipt) { await rpc({op: 'result', ...receipt}); return; }
        if (lastResult?.commandID === command.id) { await rpc({op: 'result', ...lastResult}); return; }
        if (completed.includes(command.id)) { await rpc({op: 'result', commandID: command.id, ok: true}); return; }
        let ok = false, error;
        try {
          const result = await rpc({op: 'load', accountID: command.accountID, provider: command.provider, commandID: command.id});
          if (result.ok !== true) throw Error('Session unavailable');
          validateCookies(command.provider, result.cookies);
          const {activeAccounts = {}} = await browser.storage.local.get('activeAccounts');
          // The user pairs captures with account labels. Active metadata cannot prove
          // website identity after manual login, so never auto-save outgoing cookies.
          // A process crash after this receipt must never replay the mutation automatically.
          await browser.storage.local.set({receipts: [...receipts, {commandID: command.id, ok: false, error: 'Session transaction interrupted; inspect browser sign-in'}].slice(-1000)});
          await applySession(browser.cookies, command.provider, result.cookies);
          await browser.storage.local.set({activeAccounts: {...activeAccounts, [command.provider]: command.accountID}});
          await browser.storage.local.set({completed: [...completed, command.id].slice(-1000)});
          ok = true;
          status = 'Website cookies applied; server account not verified';
          const tabs = await browser.tabs.query({});
          for (const tab of tabs) {
            if (tab.incognito || !tab.url || tab.id === undefined) continue;
            const url = new URL(tab.url);
            if (url.protocol === 'https:' && allowedHost(command.provider, url.hostname)) await browser.tabs.reload(tab.id).catch(() => {});
          }
        } catch (e) { error = e.message.includes('rollback') ? e.message : 'Session could not be applied'; status = error; }
        // Persist failed results as well: retries must never silently repeat a destructive switch.
        const savedResult = {commandID: command.id, ok, ...(error ? {error} : {})};
        await browser.storage.local.set({lastResult: savedResult, receipts: [...receipts.filter(r => r.commandID !== command.id), savedResult].slice(-1000)});
        await rpc({op: 'result', commandID: command.id, ok, ...(error ? {error} : {})});
      }).catch(() => { status = 'SubscriptionBar disconnected; result pending'; }).finally(() => processing.delete(command.id));
    }
  } catch { status = 'SubscriptionBar unavailable or incompatible'; }
  finally { polling = false; }
}
async function connect() {
  if (port) return;
  const stored = await browser.storage.local.get('browserInstanceID');
  instanceID = stored.browserInstanceID || crypto.randomUUID();
  await browser.storage.local.set({browserInstanceID: instanceID});
  port = browser.runtime.connectNative(HOST);
  port.onMessage.addListener(message => {
    if (!message || typeof message.requestID !== 'string') return;
    const request = requests.get(message.requestID);
    if (!request) return;
    clearTimeout(request.timer); requests.delete(message.requestID); request.resolve(message);
  });
  port.onDisconnect.addListener(() => {
    void browser.runtime.lastError;
    port = undefined; status = 'SubscriptionBar disconnected';
    for (const request of requests.values()) { clearTimeout(request.timer); request.reject(Error('Disconnected')); }
    requests.clear();
  });
  const {lastResult} = await browser.storage.local.get('lastResult');
  if (lastResult) await rpc({op: 'result', ...lastResult}).catch(() => {});
  await poll();
}
browser.runtime.onMessage.addListener((message, sender, reply) => {
  if (sender.id !== browser.runtime.id) return;
  if (message?.op === 'status') { reply({accounts, status}); return; }
  if (message?.op !== 'capture') return;
  serialize(async () => {
    const account = accounts.find(a => a.id === message.accountID);
    if (!account) throw Error('Select an account');
    const cookies = validateCookies(account.provider, await readCookies(browser.cookies, account.provider));
    const result = await rpc({op: 'capture', accountID: account.id, provider: account.provider, cookies});
    if (result.ok !== true) throw Error('Capture failed');
    const {activeAccounts = {}} = await browser.storage.local.get('activeAccounts');
    await browser.storage.local.set({activeAccounts: {...activeAccounts, [account.provider]: account.id}});
    status = 'Website cookies saved; confirm this is the selected account';
    return {ok: true, status};
  }).then(reply, () => reply({ok: false, status: 'Capture failed. Check the app and sign into the selected website account.'}));
  return true;
});
browser.alarms.create('reconnect', {periodInMinutes: 0.5});
browser.alarms.onAlarm.addListener(() => { if (!port) connect().catch(() => {}); else poll(); });
setInterval(poll, 5000);
connect().catch(() => { status = 'SubscriptionBar unavailable'; });
