import {readFileSync, writeFileSync, mkdirSync, cpSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root = new URL('./', import.meta.url);
const output = new URL('firefox/', root);
mkdirSync(output, {recursive: true});
const manifest = JSON.parse(readFileSync(new URL('manifest.json', root), 'utf8'));
delete manifest.key;
manifest.background = {scripts: ['background.js']};
manifest.browser_specific_settings = {gecko: {id: 'subscriptionbar@local.example', strict_min_version: '140.0', data_collection_permissions: {required: ['authenticationInfo', 'websiteContent']}}};
writeFileSync(new URL('manifest.json', output), JSON.stringify(manifest, null, 2) + '\n');
const cookies = readFileSync(new URL('cookies.mjs', root), 'utf8').replace(/^export /gm, '');
const background = readFileSync(new URL('background.js', root), 'utf8').replace(/^import .*from '\.\/cookies\.mjs';\n/, '').replace(/\bchrome\./g, 'browser.');
writeFileSync(new URL('background.js', output), '// Generated by ../build-firefox.mjs; edit shared sources.\n' + cookies + '\n' + background);
for (const file of ['popup.html', 'popup.js', 'i18n.js']) {
  let source = readFileSync(new URL(file, root), 'utf8');
  if (file.endsWith('.js')) source = source.replace(/\bchrome\./g, 'browser.');
  writeFileSync(new URL(file, output), source);
}
cpSync(new URL('_locales/', root), new URL('_locales/', output), {recursive: true});
console.log(fileURLToPath(output));
